### PR TITLE
readme.md update

### PR DESCRIPTION
**Pull request by CPJB**
Added some more info to configuration
Added Service section

### CODE REVIEW

**Comment by Sean-Der** [comment]
Oh nice! Thank you very much for making this PR

Would you mind squashing that all into one commit? (Or giving me permission too, I don't want to modify your work unless you are ok with it)

**Comment by CPJB** [comment]
Shure. NP. I think this should do it. Not very much into github.

**Comment by CPJB** [comment]
I have added one more commit after this pull request.

**Comment by Sean-Der** [comment]
Oof, better late than never.

I squashed and merged your work https://github.com/Sean-Der/fail2rest/commit/3e2a54a130c86e74f6b1b63b346377eca4839734! Thank you for making fail2rest better :)

**Pull request closed without merging**
